server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/web?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: root


mybatis-plus:
  #MyBatis Mapper 所对应的 XML 文件位置
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.demon.spring.pojo
  configuration:
    #默认false,是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    mapUnderscoreToCamelCase: false


logging:
  level:
    com.demon.spring: debug